### ISSUE TITLE
RepeatedTask metric labels are incorrect

### ISSUE THREAD

**Issue by jdm-square** [cashapp/wisp#90]
https://github.com/cashapp/wisp/blob/98ed57db7ef4ed79ef0f2760fe8a127566f54849/wisp-task/src/main/kotlin/wisp/task/RepeatedTaskMetrics.kt#L20 looks like it's trying to add two labels to the metric, `name` and `result`. There are two problems here:
* that `tag` method actually takes `key` and `value` parameters, so we are adding one label named `name` and recording the value `result`
* there's no attempt to pass correct tags when recording the metric in https://github.com/cashapp/wisp/blob/main/wisp-task/src/main/kotlin/wisp/task/RepeatedTask.kt#L108

**Comment by jdm-square** [comment]
I've been trying to write a pull request that fixes this and adds tests that metrics are being recorded as expected, but I am having a very difficult time getting a usable metric registry in unit tests.

**Comment by jdm-square** [comment]
@chris-ryan-square Are there any examples of validating metrics in unit tests for wisp that I can follow?

**Comment by chris-ryan-square** [comment]
Not that I am aware of - I think the only reference to metrics is in wisp-task
